language: c

compiler:
  - clang
  - gcc

env:
  # build without shadowsocks protocol
  - ENABLE_SS: OFF
    USE_CRYPTO_OPENSSL: OFF
    USE_CRYPTO_MBEDTLS: OFF

  # build with openssl library
  - ENABLE_SS: ON
    USE_CRYPTO_OPENSSL: ON
    USE_CRYPTO_MBEDTLS: OFF

  # build with mbed TLS library
  #- ENABLE_SS: ON
  #  USE_CRYPTO_OPENSSL: OFF
  #  USE_CRYPTO_MBEDTLS: ON

  # build https proxy with openssl library
  - ENABLE_SS: ON
    ENABLE_HTTPS_PROXY: ON
    USE_CRYPTO_OPENSSL: ON
    USE_CRYPTO_MBEDTLS: OFF

sudo: false

branches:
  except:
    - /^v[0-9]/

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
      - scons
      - libssl-dev
      - libevent-dev

script:
  - scons && scons --clean
  - mkdir -p build && cd build && cmake .. -DENABLE_HTTPS_PROXY:STRING=$ENABLE_HTTPS_PROXY -DENABLE_SS:STRING=$ENABLE_SS -DUSE_CRYPTO_OPENSSL:STRING=$USE_CRYPTO_OPENSSL && make

notifications:
  recipients:
    - boycht@gmail.com
  email:
    on_success: change
    on_failure: always

# vim:set sts=2 sw=2 tw=0 et:
