language: c

compiler:
  - clang
  - gcc

sudo: false

branches:
  except:
    - /^v[0-9]/

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
      - scons
      - libssl-dev
      - libevent-dev

script:
  - scons
  - mkdir -p build && cd build && cmake .. -DENABLE_SS:STRING=ON -DUSE_CRYPTO_OPENSSL:STRING=ON && make

notifications:
  recipients:
    - boycht@gmail.com
  email:
    on_success: change
    on_failure: always

# vim:set sts=2 sw=2 tw=0 et:
