
# build mproxy on AppVeyor - https://ci.appveyor.com

shallow_clone: true
clone_depth: 10

version: '{build}'
os:
- Visual Studio 2015

environment:
  BOOST_ROOT: C:\Libraries\boost_1_59_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_59_0\lib64-msvc-14.0

install:
- '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64'
- cd \
  # OpenSSL
  # Unfurtunately, OpenSSL version below needs constant update (2 places) because old versions are quickly deleted.
- appveyor DownloadFile https://slproweb.com/download/Win64OpenSSL-1_0_2g.exe
- ps: Start-Process Win64OpenSSL-1_0_2g.exe -ArgumentList "/silent /verysilent /sp- /suppressmsgboxes" -Wait
  # Libevent
- appveyor DownloadFile https://github.com/libevent/libevent/releases/download/release-2.0.21-stable/libevent-2.0.21-stable.tar.gz
- 7z x libevent-2.0.21-stable.tar.gz -so | 7z x -si -ttar > nul
- cd libevent-2.0.21-stable
- nmake -f Makefile.nmake
- mkdir lib
- move *.lib lib\
- move WIN32-Code\event2\* include\event2\
- move *.h include\
- cd ..
  #
- cd %APPVEYOR_BUILD_FOLDER%


build_script:
- set PATH=C:\ProgramData\chocolatey\bin;C:\apache-ant-1.9.6\bin;%PATH%
- set JAVA_HOME=C:\Program Files\Java\jdk1.7.0
- set PATH=%JAVA_HOME%\bin;%PATH%
# - set PATH=%PATH%;C:\Program Files (x86)\Haskell Platform\2014.2.0.0\bin
# - set PATH=%PATH%;C:\Program Files (x86)\Haskell Platform\2014.2.0.0\lib\extralibs\bin
- set PATH=C:\Python27-x64\scripts;C:\Python27-x64;%PATH%
- mkdir cmake-build
- cd cmake-build
- cmake -G "Visual Studio 14 2015 Win64" -DENABLE_SS:STRING=ON -DUSE_CRYPTO_OPENSSL:STRING=ON -DLIBEVENT_ROOT=C:\libevent-2.0.21-stable -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" ..
- cmake --build . --config Release
# TODO: 
# - cpack
# - ctest 

