
# build mproxy on AppVeyor - https://ci.appveyor.com

#shallow_clone: true
clone_depth: 10

version: '{build}'
os:
- Visual Studio 2015

environment:
  BOOST_ROOT: C:\Libraries\boost_1_59_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_59_0\lib64-msvc-14.0

  matrix:
    # build without shadowsocks protocol
    - ENABLE_SS: OFF
      USE_CRYPTO_OPENSSL: OFF
      USE_CRYPTO_MBEDTLS: OFF
      BUILD_SUFFIX: "vc2015_x64"

    # build with openssl library
    - ENABLE_SS: ON
      USE_CRYPTO_OPENSSL: ON
      USE_CRYPTO_MBEDTLS: OFF
      BUILD_SUFFIX: "openssl_vc2015_x64"

    # build with mbed TLS library
    - ENABLE_SS: ON
      USE_CRYPTO_OPENSSL: OFF
      USE_CRYPTO_MBEDTLS: ON
      BUILD_SUFFIX: "mbedtls_vc2015.x64"

    # build https proxy with openssl library
    #- ENABLE_SS: ON
    #  ENABLE_HTTPS_PROXY: ON
    #  USE_CRYPTO_OPENSSL: ON
    #  USE_CRYPTO_MBEDTLS: OFF

install:
- ECHO "Filesystem root:"
- ps: "ls \"C:/\""
  # recursive clone 
- git submodule update --init --recursive --depth 3
  # VC env
- '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64'
  # mbedTLS
- cd \
- appveyor DownloadFile https://tls.mbed.org/download/mbedtls-2.6.0-apache.tgz
- 7z x mbedtls-2.6.0-apache.tgz -so | 7z x -si -ttar > nul
- cd mbedtls-2.6.0
- mkdir lib
- mkdir cmake-build
- cd cmake-build
- cmake -G "Visual Studio 14 2015 Win64" .. 
- cmake --build . --config Release --target mbedtls
- move library\Release\*.lib ..\lib\
  # Libevent
- cd \
- appveyor DownloadFile https://github.com/libevent/libevent/releases/download/release-2.1.8-stable/libevent-2.1.8-stable.tar.gz
- 7z x libevent-2.1.8-stable.tar.gz -so | 7z x -si -ttar > nul
- cd libevent-2.1.8-stable
- nmake -f Makefile.nmake static_libs
- mkdir lib
- move *.lib lib\
- move WIN32-Code\nmake\event2\* include\event2\
- move *.h include\
- cd ..
  # 
- cd %APPVEYOR_BUILD_FOLDER%


build_script:
- set PATH=C:\ProgramData\chocolatey\bin;C:\apache-ant-1.9.6\bin;%PATH%
- set JAVA_HOME=C:\Program Files\Java\jdk1.7.0
- set PATH=%JAVA_HOME%\bin;%PATH%
# - set PATH=%PATH%;C:\Program Files (x86)\Haskell Platform\2014.2.0.0\bin
# - set PATH=%PATH%;C:\Program Files (x86)\Haskell Platform\2014.2.0.0\lib\extralibs\bin
- set PATH=C:\Python27-x64\scripts;C:\Python27-x64;%PATH%
- mkdir cmake-build
- cd cmake-build
- cmake -G "Visual Studio 14 2015 Win64" -DENABLE_HTTPS_PROXY:STRING="%ENABLE_HTTPS_PROXY%" -DENABLE_SS:STRING="%ENABLE_SS%" -DUSE_CRYPTO_OPENSSL:STRING="%USE_CRYPTO_OPENSSL%" -DUSE_CRYPTO_MBEDTLS="%USE_CRYPTO_MBEDTLS%" -DLIBEVENT_ROOT=C:\libevent-2.1.8-stable -DMBEDTLS_ROOT_DIR=C:\mbedtls-2.6.0 -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" ..
- cmake --build . --config Release
# TODO: 
# - cpack
# - ctest 

artifacts:
- path: cmake-build\Release
  name: mproxy_$(BUILD_SUFFIX)

deploy:
  release: mproxy_v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: wFxle0z6fJTg0aVgEyl46GbOPGvVb/WvnNmmO5ifTaBQx5Q3qlhlfwwIpuABfuty 
  artifact: /mproxy_.*_x64/
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only

