
# build mproxy on AppVeyor - https://ci.appveyor.com

#shallow_clone: true
clone_depth: 10

version: '{build}'
os:
- Visual Studio 2015

environment:
  BOOST_ROOT: C:\Libraries\boost_1_59_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_59_0\lib64-msvc-14.0

install:
- ECHO "Filesystem root:"
- ps: "ls \"C:/\""
  # recursive clone 
- git submodule update --init --recursive --depth 3
  # VC env
- '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64'
  # mbedTLS
- cd \
- appveyor DownloadFile https://tls.mbed.org/download/mbedtls-2.2.1-apache.tgz
- 7z x mbedtls-2.2.1-apache.tgz -so | 7z x -si -ttar > nul
- cd mbedtls-2.2.1
- mkdir lib
- mkdir cmake-build
- cd cmake-build
- cmake ..
- cmake --build . --config Release --target mbedtls
- move library\Release\*.lib ..\lib\
  # Libevent
- cd \
- appveyor DownloadFile https://github.com/libevent/libevent/releases/download/release-2.0.22-stable/libevent-2.0.22-stable.tar.gz
- 7z x libevent-2.0.22-stable.tar.gz -so | 7z x -si -ttar > nul
- cd libevent-2.0.22-stable
- nmake -f Makefile.nmake
- mkdir lib
- move *.lib lib\
- move WIN32-Code\event2\* include\event2\
- move *.h include\
- cd ..
  # 
- cd %APPVEYOR_BUILD_FOLDER%


build_script:
- set PATH=C:\ProgramData\chocolatey\bin;C:\apache-ant-1.9.6\bin;%PATH%
- set JAVA_HOME=C:\Program Files\Java\jdk1.7.0
- set PATH=%JAVA_HOME%\bin;%PATH%
# - set PATH=%PATH%;C:\Program Files (x86)\Haskell Platform\2014.2.0.0\bin
# - set PATH=%PATH%;C:\Program Files (x86)\Haskell Platform\2014.2.0.0\lib\extralibs\bin
- set PATH=C:\Python27-x64\scripts;C:\Python27-x64;%PATH%
- mkdir cmake-build
- cd cmake-build
- cmake -G "Visual Studio 14 2015 Win64" -DENABLE_SS:STRING=ON -DUSE_CRYPTO_OPENSSL:STRING=OFF -DUSE_CRYPTO_MBEDTLS=ON -DLIBEVENT_ROOT=C:\libevent-2.0.22-stable -DMBEDTLS_ROOT_DIR=C:\mbedtls-2.2.1 -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" ..
- cmake --build . --config Release
# TODO: 
# - cpack
# - ctest 

artifacts:
- path: cmake-build\Release
  name: mproxy_x64
